name: build

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Figure out docker image tag
        id: taggen
        uses: docker/metadata-action@v3
        with:
          images: |
            quay.io/yuvipanda/nbss
          tags: |
            type=sha

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.taggen.outputs.tags }}

      - name: Image Tag
        run: echo ${{ steps.taggen.outputs.tags }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ae152475-dc79-474c-8937-6b7dfe14fde3

      - uses: azure/setup-helm@v3
        name: Install Helm

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy nbss
        run: |
          helm upgrade --install --namespace nbss --create-namespace \
            nbss helm/nbss \
            --set env.AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            --set env.AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
            --set image.tag="${{ fromJSON(steps.taggen.outputs.json).labels['org.opencontainers.image.version'] }}"

      - uses: azure/setup-kubectl@v1
        name: install kubectl

      - name: Wait for the deployment to be active
        run: |
          kubectl --namespace=nbss \
            wait --for=condition=available --timeout=60s --all deployments
