name: build

on:
  push:
    branches: main
  pull_request:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - uses: azure/setup-helm@v3
        name: Install Helm

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup dev dependencies (chartpress, etc)
        run: |
          pip install -r dev-requirements.txt

      - name: Login to Quay.io
        uses: docker/login-action@v1
        # Run this only on merge
        if: "${{ github.event_name == 'push' }}"
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup push rights to gh-pages
        # Run this only on merge
        if: "${{ github.event_name == 'push' }}"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.CHARTPRESS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Run chartpress
        run: |
          cd helm
          chartpress
          git diff
